# Site settings
title: Luu Gia Thuy
name: Luu Gia Thuy
email: luugiathuy@gmail.com
baseurl: ""
url: http://luugiathuy.com
description: My name is Luu Gia Thuy. I am from Vietnam. I'm passionate about software engineer, mobile application, programming language and best practices of code.
twitter_username: luugiathuy
github_username: luugiathuy
linkedin_username: luugiathuy

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /:year/:month/:title/
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - README.md
  - reveal.js/index.html
  - reveal.js/plugin/markdown/example.html
  - reveal.js/plugin/notes/notes.html
  - reveal.js/plugin/notes-server/notes.html
  - reveal.js/test/
  - reveal.js/*.md
  - reveal.js/Gruntfile.js
  - reveal.js/package.json
  - reveal.js/LICENSE
